FROM golang:1.17.2

ENV VERSION v1.0.25
ENV GOCACHE /tmp
WORKDIR /go/src/github/mlabouardy/movies-parser

RUN wget https://github.com/sonatype-nexus-community/nancy/releases/download/v1.0.25/nancy-v1.0.25-linux-amd64 -O nancy && \
    chmod +x nancy && mv nancy /usr/local/bin/nancy


RUN  go get -u golang.org/x/lint/golint

COPY . .
RUN go get -v
